# Generated by Django 6.0.5 on 2026-05-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(choices=[('youth', 'Youth Programs'), ('internship', 'Internship Activities'), ('community', 'Community Projects'), ('award', 'Student Awards')], max_length=20),
        ),
    ]
