# Generated by Django 6.0.5 on 2026-05-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='e.g., Student Participant, School Partner', max_length=100)),
                ('quote', models.TextField(help_text='The feedback or quote text')),
                ('image', models.ImageField(blank=True, help_text='Optional author picture', null=True, upload_to='testimonials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
