# Generated by Django 6.0.5 on 2026-05-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=200)),
                ('creator_email', models.EmailField(max_length=254)),
                ('club_name', models.CharField(max_length=300)),
                ('organization', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JoinClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(blank=True, max_length=300)),
                ('interest', models.CharField(max_length=200)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
